server:
  port: 8088

spring:
  datasource:
    username: root
    password: zsm-mysql
    url: jdbc:mysql://localhost/blog?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 指定 Druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置， DataSourceProperties 中没有相关属性，默认无法绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 25
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    druid:
      test-on-borrow: true
      test-while-idle: true
  servlet: # 添加多文件上传
    multipart:
      enabled: true
      max-file-size: 20MB
  influx:
    password:
  # 邮件配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1097646307@qq.com
    password: cjdxmutvxqckgaga
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zsm.springboot.entity  # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml

# pagehelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  page-size-zero: false
#  returnPageInfo: check

jwt:
  config:
    key: passbyzsm
    ttl: 604800000

# 自定义图片上传路径
uploadpath:
  location:
    windows: /E:/IDEA/images/
    linux: /usr/java/springboot/images/
